import os
# Must be done BEFORE importing torch
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

import shutil
import argparse
from .validate import Validator
from .cg_slice import CgSlice
from fuzzpilot.pilot import FuzzPilot

def get_fuzzer ():
    honggfuzz = shutil.which("honggfuzz")
    if honggfuzz is None:
        print("Error: honggfuzz not found in PATH.")
        exit(1)
    return honggfuzz


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", "--bench",  type=str, default="", help="the benchmark directory")
    parser.add_argument('-a', '--avg', action="store_true", default=False, help='schedule the driver by average')
    parser.add_argument('-s', '--static', action="store_true", default=False, help='schedule the driver by static priority')
    parser.add_argument('-r', '--random', action="store_true", help='schedule the driver randomly')
    parser.add_argument('-m', '--max_time', help='the max fuzzing time')
    parser.add_argument('-t', '--time_budget', help='the time out for staying at one driver without fcov change')
    parser.add_argument('--driver-id', type=int, default=0, help='force start with a specific driver id (debug)')
    # Ablation study parameters
    parser.add_argument('--disable-embed-drift', action='store_true', default=False, help='Disable embedding drift feature for ablation')
    parser.add_argument('--disable-fcov-drift', action='store_true', default=False, help='Disable function coverage drift feature for ablation')
    

    # Validation fuzzing results
    parser.add_argument('--validate', help='Validation fuzzing results: re-run each driver with the curpos generated by fuzzer')

    # Slice CG BY depth
    parser.add_argument('--cgslice', type=int, help='The max depth of the call graph to consider')
    parser.add_argument('--drvinfo', type=str, default="", help='statistic final driver info')
    
    args = parser.parse_args()

    if args.validate:
        import shlex
        v = Validator (args.bench, shlex.split(args.validate))
        v.run_all()
        return

    if args.cgslice:
        CgSlice(args.bench, args.cgslice).slice()
        return
    
    if args.drvinfo:
        CgSlice(args.bench, "").stat(args.drvinfo)
        return

    honggfuzz = get_fuzzer ()
    fp = FuzzPilot(honggfuzz, args.disable_embed_drift, args.disable_fcov_drift)

    # default 24h
    max_time_budget = 24*3600
    if args.max_time != None:
        max_time_budget = int(args.max_time)

    # default 1min
    driver_time_budget = 60
    if args.time_budget != None:
        driver_time_budget = int(args.time_budget)  

    if args.avg:
        fp.start_fuzzer(args.bench, args.driver_id if args.driver_id else 1)
        try:
            fp.run_schedule_average(max_time_budget)
        except KeyboardInterrupt:
            fp.stop_fuzzer()
    elif args.random:
        fp.start_fuzzer(args.bench, args.driver_id if args.driver_id else 1)
        try:
            fp.run_schedule_random(driver_time_budget, max_time_budget)
        except KeyboardInterrupt:
            fp.stop_fuzzer()
    elif args.static:
        fp.start_fuzzer(args.bench, args.driver_id if args.driver_id else 1)
        try:
            fp.run_schedule_static(driver_time_budget, max_time_budget)
        except KeyboardInterrupt:
            fp.stop_fuzzer()
    else:
        fp.start_fuzzer(args.bench, args.driver_id if args.driver_id else 0)
        try:
            if fp.is_single_driver_mode():
                fp.run_single_driver(max_time_budget)
            else:
                fp.run_schedule(driver_time_budget, max_time_budget)
        except KeyboardInterrupt:
            fp.stop_fuzzer()

if __name__ == "__main__":
    main()

